estimator:
  # - name: random-forest-classifier
  #   params:      
  #     class_weight: balanced_subsample
  # - name: KMeans
  #   params:
  #     n_clusters: 2
  - name: logistic_regression
    params:
      random_state: 0

stage: h_1    

data:
  filepath: ./dataset/train_classification.csv

metrics:
  #- name: mean absolute error
  #  params: {}
  - name: f1 Score
    params: {}

search:
  jobs: -1
  grid:
    - name: logistic_regression
      params:
        #n_estimators: [50, 100, 200]
        #n_init: [5, 10, 15, 20, 25, 30, 35]
        solver: [newton-cg,lbfgs,liblinear,sag,saga]


export:
  output_dir: models

reports:
  dir: reports
